### ISSUE TITLE
image stretched out

### ISSUE THREAD

**Issue by ColombianJulio** [wsaunders1014/scene-transitions#1]
can't determine the correct image size. whenever upload an image for transition, it just seems to stretch the image and without some way to fix it, I'm having to edit the image first before I can upload it.i will attach the original image and what it looks like from the scene transitions.
![Dodger Hall](https://user-images.githubusercontent.com/67991100/91962132-1eae8180-ecda-11ea-83f2-6d9c5557ea90.jpg)
![Screen Shot 2020-09-02 at 5 04 13 AM](https://user-images.githubusercontent.com/67991100/91962142-22420880-ecda-11ea-97b0-d6bef69d0bef.png)

**Comment by wsaunders1014** [comment]
Well the css is set to cover, which stretches the image to fit the whole screen. so the optimal image size would be your monitor's resolution essentially. At the moment this is the intended effect, however I can add an option to choose how to apply the image in the future.
