### ISSUE TITLE
the project is abandoned?

### ISSUE THREAD

**Issue by altair984** [wsaunders1014/scene-transitions#11]
Hello, I would like to know if the project is abandoned or still in progress. Personally I loved it but it's been a while since I've been able to work with the module. He doesn't let me accept it and doesn't make any compromises. Greetings and thank you very much for all your work. I hope you continue because it is a great module.

**Comment by brunocalado** [comment]
up

**Comment by DM-miX** [comment]
I'm taking this one over from Will. Stay tuned!

**Comment by DM-miX** [comment]
0.0.8 just released fixing up some critical bugs and FVTT 0.8 support
