### ISSUE TITLE
Set sound volume

### ISSUE THREAD

**Issue by Danii0206** [wsaunders1014/scene-transitions#13]
Hi,

it would be helpful if we could set a volume for the sound. As is it gets blasted at full volume. Not always a good idea. ;)

Kind regards
Danii

**Comment by DM-miX** [comment]
This is a great idea!
I'm working on moving audio to the new Web Audio API in Foundry 0.8. I'll see what I can do

**Comment by DM-miX** [comment]
Done in 0.0.9
