### ISSUE TITLE
Macro for transition with sound

### ISSUE THREAD

**Issue by jacksands** [wsaunders1014/scene-transitions#15]
Can someone help with a macro like on README.md  but with sound options?

Tks!

**Comment by jacksands** [comment]
MACRO CREATED BY MESTRE DIGITAL!  https://www.youtube.com/watch?v=q2L1DLlWvJg&t=256s

/*``

*/

const scenename = '454'; // Scene Name | Nome da Cena
const backgroundImage = 'worlds/cycleofcerberusdw/images/cerberus.webp'; // Imagem de Fundo | false apenas executa transição
const content = "<p>TEXTO</p><p>TEXTO</p><p>TEXTO</p>"; // Text | Texto da Cena
const audio = 'worlds/cycleofcerberusdw/sounds/cerberus.ogg'; // Sound | Som 
const delay = 5000; // ms = 1000 == 1 second | 1000 == 1 segundo

// -------------------------------------------------------
//let scene = game.scenes.entries.find(s => s.data.name === scenename);
let myscene = game.scenes.getName(scenename);

let data = {
	sceneID: myscene.id,  //sceneID: FALSE for transition without scene change
	options:{
		fontColor:'#ffffff',
		fontSize:'18px',
		bgImg: backgroundImage, 
		bgPos:'center center',
		bgSize:'cover',  
		bgColor:'#333333',
		bgOpacity:0.7,
    audio: audio,
		delay: delay, //how long for transition to stay up
		skippable:true, //Allows players to skip transition with a click before delay runs out.
		content: content,
	}
}

activeTransition = new Transition(false, data.sceneID, data.options) //
activeTransition.render()// These 2 lines can be omitted if you don't want to personally see the transition.
game.socket.emit('module.scene-transitions', data);

// BGSIZE   // contain - Resize the background image to make sure the image is fully visible
            //cover -	Resize the background image to cover the entire container, even if it has to stretch the //image or cut a little bit off one of the edges
			//auto	- Default value. The background image is displayed in its original size

**Comment by DM-miX** [comment]
Hi Jacksands - yep you got it
        
`audio:"worlds/myworld/mytrack.mp3",`

You can also use:
```
        fadeIn: 1000,
        fadeOut: 2000,
```
Should add these to the readme :)

**Comment by jacksands** [comment]
Tks!!!! appreciate!
