### ISSUE TITLE
module.json references version 0.0.8, which isn't released

### ISSUE THREAD

**Issue by Mitchrock** [wsaunders1014/scene-transitions#18]
As the title says, module.json references version 0.0.8 in releases but there is no 0.0.8 release build. Because of this you can't update or install the module through Foundry; it just gives a "not found" error.

**Comment by Mitchrock** [comment]
Side note to anyone else unable to install the module in Foundry: you can manually install version 0.0.7 by going [here](https://github.com/wsaunders1014/scene-transitions/releases/download/0.0.7/scene-transitions.zip) and extracting the .zip into a folder called scene-transitions in your modules folder, at least until 0.0.8 is actually released.

**Comment by wsaunders1014** [comment]
This has been fixed, sorry.
