### ISSUE TITLE
Volume adjustment for audio linked to transition?

### ISSUE THREAD

**Issue by Spectre-63** [wsaunders1014/scene-transitions#22]
What are valid values for the "Background Size"?  I tried putting in a resolution, but it didn't appear to affect the output.

Thanks for adding the volume slider!

**Comment by DM-miX** [comment]
[https://cssreference.io/property/background-size/](https://cssreference.io/property/background-size/)
These should all be valid - personally I've never used anything other than 'cover'. So I'm not sure what works.
I'll have to find some time for experimentation

**Comment by DM-miX** [comment]
I tried several values drom that reference all worked
