### ISSUE TITLE
[Feature Request] Add a "manual ending" for transition. 

### ISSUE THREAD

**Issue by vsthem** [wsaunders1014/scene-transitions#23]
Allow the user to manually "trigger" the end of the transition, instead of setting a time. This would allow the GM to talk over the transition and trigger the end of the transition when they're finished speaking.

**Comment by DM-miX** [comment]
I was actually thinking about this the other day. It’ll be pretty easy to do.

**Comment by DM-miX** [comment]
Added in 0.1.1 (to be released shortly)
